# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField()),
                ('signature', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_year', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Semester'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Show'),
        ),
        migrations.AddField(
            model_name='membership',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Schedule'),
        ),
        migrations.AddField(
            model_name='membership',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Show'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Semester'),
        ),
    ]
