# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='seniority_offset',
            field=models.IntegerField(default=0),
        ),
    ]
