# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0004_volunteer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.DateTimeField(),
        ),
    ]
