# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0005_auto_20160404_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='alternating',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
