# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0006_schedule_alternating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinitronProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spinitron_name', models.CharField(max_length=150)),
                ('dj_name', models.CharField(max_length=150)),
                ('spinitron_email', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('N', 'New User'), ('U', 'User'), ('E', 'Editor'), ('A', 'Admin')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signature_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 4, 2, 31, 929214)),
        ),
    ]
