# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 08:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0007_auto_20160409_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='spinitron',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dj_summary.SpinitronProfile'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signature_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 4, 4, 15, 701973)),
        ),
    ]
