# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0008_auto_20160409_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='signature_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 4, 21, 24, 227383)),
        ),
        migrations.AlterField(
            model_name='spinitronprofile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
