# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj_summary', '0009_auto_20160409_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('length', models.IntegerField()),
                ('alternating', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Semester')),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='djs',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='show',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signature_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 15, 57, 41, 91512)),
        ),
        migrations.AlterField(
            model_name='show',
            name='semesters',
            field=models.ManyToManyField(through='dj_summary.Timeslot', to='dj_summary.Semester'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Show'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_summary.Show'),
        ),
        migrations.AddField(
            model_name='show',
            name='djs',
            field=models.ManyToManyField(through='dj_summary.Assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
