# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0010_auto_20160411_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='signature_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 17, 8, 0, 841268)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='alternating',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot',
            field=models.IntegerField(null=True),
        ),
    ]
