# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 21:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0011_auto_20160411_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='signature_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 11, 17, 20, 27, 120741)),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot',
            field=models.IntegerField(default=-1),
        ),
    ]
