# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_summary', '0012_auto_20160411_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='subbing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='signature_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 14, 15, 48, 23, 819317)),
        ),
    ]
